using System.Collections.Immutable;
using System.Collections.ObjectModel;

namespace activities8.Utils;

public class Countries
    {
        public static readonly ImmutableList<(int, string, int)> ListCountries = ImmutableList.Create(
            (1, "Afghanistan", 41),
            (2, "Albania", 42),
            (3, "Algeria", 43),
            (4, "Andorra", 44),
            (5, "Angola", 45),
            (6, "Antigua and Barbuda", 46),
            (7, "Argentina", 47),
            (8, "Armenia", 48),
            (9, "Australia", 49),
            (10, "Austria", 50),
            (11, "Azerbaijan", 51),
            (12, "Bahamas", 52),
            (13, "Bahrain", 53),
            (14, "Bangladesh", 54),
            (15, "Barbados", 55),
            (16, "Belarus", 56),
            (17, "Belgium", 57),
            (18, "Belize", 58),
            (19, "Benin", 59),
            (20, "Bhutan", 60),
            (21, "Bolivia", 61),
            (22, "Bosnia and Herzegovina", 62),
            (23, "Botswana", 63),
            (24, "Brazil", 64),
            (25, "Brunei", 65),
            (26, "Bulgaria", 66),
            (27, "Burkina Faso", 67),
            (28, "Burundi", 68),
            (29, "Cabo Verde", 69),
            (30, "Cambodia", 70),
            (31, "Cameroon", 71),
            (32, "Canada", 72),
            (33, "Central African Republic", 73),
            (34, "Chad", 74),
            (35, "Chile", 75),
            (36, "China", 76),
            (37, "Colombia", 77),
            (38, "Comoros", 78),
            (39, "Congo", 79),
            (40, "Costa Rica", 80),
            (41, "Côte d'Ivoire", 81),
            (42, "Croatia", 82),
            (43, "Cuba", 83),
            (44, "Cyprus", 84),
            (45, "Czech Republic", 85),
            (46, "Denmark", 86),
            (47, "Djibouti", 87),
            (48, "Dominica", 88),
            (49, "Dominican Republic", 89),
            (50, "DR Congo", 90),
            (51, "Ecuador", 91),
            (52, "Egypt", 92),
            (53, "El Salvador", 93),
            (54, "Equatorial Guinea", 94),
            (55, "Eritrea", 95),
            (56, "Estonia", 96),
            (57, "Eswatini", 97),
            (58, "Ethiopia", 98),
            (59, "Fiji", 99),
            (60, "Finland", 100),
            (61, "France", 101),
            (62, "Gabon", 102),
            (63, "Gambia", 103),
            (64, "Georgia", 104),
            (65, "Germany", 105),
            (66, "Ghana", 106),
            (67, "Gibraltar", 107),
            (68, "Greece", 108),
            (69, "Grenada", 109),
            (70, "Guatemala", 110),
            (71, "Guinea", 111),
            (72, "Guinea-Bissau", 112),
            (73, "Guyana", 113),
            (74, "Haiti", 114),
            (75, "Honduras", 115),
            (76, "Hong Kong", 116),
            (77, "Hungary", 117),
            (78, "Iceland", 118),
            (79, "India", 119),
            (80, "Indonesia", 120),
            (81, "Iran", 121),
            (82, "Iraq", 122),
            (83, "Ireland", 123),
            (84, "Israel", 124),
            (85, "Italy", 125),
            (86, "Jamaica", 126),
            (87, "Japan", 127),
            (88, "Jordan", 128),
            (89, "Kazakhstan", 129),
            (90, "Kenya", 130),
            (91, "Kiribati", 131),
            (92, "Kuwait", 132),
            (93, "Kyrgyzstan", 133),
            (94, "Laos", 134),
            (95, "Latvia", 135),
            (96, "Lebanon", 136),
            (97, "Lesotho", 137),
            (98, "Liberia", 138),
            (99, "Libya", 139),
            (100, "Liechtenstein", 140),
            (101, "Lithuania", 141),
            (102, "Luxembourg", 142),
            (103, "Macao", 143),
            (104, "Madagascar", 144),
            (105, "Malawi", 145),
            (106, "Malaysia", 146),
            (107, "Maldives", 147),
            (108, "Mali", 148),
            (109, "Malta", 149),
            (110, "Martinique", 150),
            (111, "Mauritania", 151),
            (112, "Mauritius", 152),
            (113, "Mexico", 153),
            (114, "Micronesia", 154),
            (115, "Moldova", 155),
            (116, "Monaco", 156),
            (117, "Mongolia", 157),
            (118, "Montenegro", 158),
            (119, "Morocco", 159),
            (120, "Mozambique", 160),
            (121, "Myanmar", 161),
            (122, "Namibia", 162),
            (123, "Nepal", 163),
            (124, "Netherlands", 164),
            (125, "New Caledonia", 165),
            (126, "New Zealand", 166),
            (127, "Nicaragua", 167),
            (128, "Niger", 168),
            (129, "Nigeria", 169),
            (130, "North Korea", 170),
            (131, "North Macedonia", 171),
            (132, "Norway", 172),
            (133, "Oman", 173),
            (134, "Pakistan", 174),
            (135, "Panama", 175),
            (136, "Papua New Guinea", 176),
            (137, "Paraguay", 177),
            (138, "Peru", 178),
            (139, "Philippines", 179),
            (140, "Poland", 180),
            (141, "Portugal", 181),
            (142, "Puerto Rico", 182),
            (143, "Qatar", 183),
            (144, "Réunion", 184),
            (145, "Romania", 185),
            (146, "Russia", 186),
            (147, "Rwanda", 187),
            (148, "Saint Kitts and Nevis", 188),
            (149, "Saint Lucia", 189),
            (150, "Saint Vincent and the Grenadines", 190),
            (151, "Samoa", 191),
            (152, "San Marino", 192),
            (153, "Sao Tome & Principe", 193),
            (154, "Saudi Arabia", 194),
            (155, "Senegal", 195),
            (156, "Serbia", 196),
            (157, "Seychelles", 197),
            (158, "Sierra Leone", 198),
            (159, "Singapore", 199),
            (160, "Slovakia", 200),
            (161, "Slovenia", 201),
            (162, "Solomon Islands", 202),
            (163, "Somalia", 203),
            (164, "South Africa", 204),
            (165, "South Korea", 205),
            (166, "South Sudan", 206),
            (167, "Spain", 207),
            (168, "Sri Lanka", 208),
            (169, "State of Palestine", 209),
            (170, "Sudan", 210),
            (171, "Suriname", 211),
            (172, "Sweden", 212),
            (173, "Switzerland", 213),
            (174, "Syria", 214),
            (175, "Taiwan", 215),
            (176, "Tajikistan", 216),
            (177, "Tanzania", 217),
            (178, "Thailand", 218),
            (179, "Timor-Leste", 219),
            (180, "Togo", 220),
            (181, "Tonga", 221),
            (182, "Trinidad and Tobago", 222),
            (183, "Tunisia", 223),
            (184, "Turkey", 224),
            (185, "Turkmenistan", 225),
            (186, "Tuvalu", 226),
            (187, "Uganda", 227),
            (188, "Ukraine", 228),
            (189, "United Arab Emirates", 229),
            (190, "United Kingdom", 230),
            (191, "United States", 231),
            (192, "Uruguay", 232),
            (193, "Uzbekistan", 233),
            (194, "Vanuatu", 234),
            (195, "Venezuela", 235),
            (196, "Vietnam", 236),
            (197, "Yemen", 237),
            (198, "Zambia", 238),
            (199, "Zimbabwe", 239)
        );

        public static readonly ImmutableList<(byte, string, byte)> ListCountriesByte = ImmutableList.Create(
            ((byte)1, "Afghanistan", (byte)41),
            ((byte)2, "Albania", (byte)42),
            ((byte)3, "Algeria", (byte)43),
            ((byte)4, "Andorra", (byte)44),
            ((byte)5, "Angola", (byte)45),
            ((byte)6, "Antigua and Barbuda", (byte)46),
            ((byte)7, "Argentina", (byte)47),
            ((byte)8, "Armenia", (byte)48),
            ((byte)9, "Australia", (byte)49),
            ((byte)10, "Austria", (byte)50),
            ((byte)11, "Azerbaijan", (byte)51),
            ((byte)12, "Bahamas", (byte)52),
            ((byte)13, "Bahrain", (byte)53),
            ((byte)14, "Bangladesh", (byte)54),
            ((byte)15, "Barbados", (byte)55),
            ((byte)16, "Belarus", (byte)56),
            ((byte)17, "Belgium", (byte)57),
            ((byte)18, "Belize", (byte)58),
            ((byte)19, "Benin", (byte)59),
            ((byte)20, "Bhutan", (byte)60),
            ((byte)21, "Bolivia", (byte)61),
            ((byte)22, "Bosnia and Herzegovina", (byte)62),
            ((byte)23, "Botswana", (byte)63),
            ((byte)24, "Brazil", (byte)64),
            ((byte)25, "Brunei", (byte)65),
            ((byte)26, "Bulgaria", (byte)66),
            ((byte)27, "Burkina Faso", (byte)67),
            ((byte)28, "Burundi", (byte)68),
            ((byte)29, "Cabo Verde", (byte)69),
            ((byte)30, "Cambodia", (byte)70),
            ((byte)31, "Cameroon", (byte)71),
            ((byte)32, "Canada", (byte)72),
            ((byte)33, "Central African Republic", (byte)73),
            ((byte)34, "Chad", (byte)74),
            ((byte)35, "Chile", (byte)75),
            ((byte)36, "China", (byte)76),
            ((byte)37, "Colombia", (byte)77),
            ((byte)38, "Comoros", (byte)78),
            ((byte)39, "Congo", (byte)79),
            ((byte)40, "Costa Rica", (byte)80),
            ((byte)41, "Côte d'Ivoire", (byte)81),
            ((byte)42, "Croatia", (byte)82),
            ((byte)43, "Cuba", (byte)83),
            ((byte)44, "Cyprus", (byte)84),
            ((byte)45, "Czech Republic", (byte)85),
            ((byte)46, "Denmark", (byte)86),
            ((byte)47, "Djibouti", (byte)87),
            ((byte)48, "Dominica", (byte)88),
            ((byte)49, "Dominican Republic", (byte)89),
            ((byte)50, "DR Congo", (byte)90),
            ((byte)51, "Ecuador", (byte)91),
            ((byte)52, "Egypt", (byte)92),
            ((byte)53, "El Salvador", (byte)93),
            ((byte)54, "Equatorial Guinea", (byte)94),
            ((byte)55, "Eritrea", (byte)95),
            ((byte)56, "Estonia", (byte)96),
            ((byte)57, "Eswatini", (byte)97),
            ((byte)58, "Ethiopia", (byte)98),
            ((byte)59, "Fiji", (byte)99),
            ((byte)60, "Finland", (byte)100),
            ((byte)61, "France", (byte)101),
            ((byte)62, "Gabon", (byte)102),
            ((byte)63, "Gambia", (byte)103),
            ((byte)64, "Georgia", (byte)104),
            ((byte)65, "Germany", (byte)105),
            ((byte)66, "Ghana", (byte)106),
            ((byte)67, "Gibraltar", (byte)107),
            ((byte)68, "Greece", (byte)108),
            ((byte)69, "Grenada", (byte)109),
            ((byte)70, "Guatemala", (byte)110),
            ((byte)71, "Guinea", (byte)111),
            ((byte)72, "Guinea-Bissau", (byte)112),
            ((byte)73, "Guyana", (byte)113),
            ((byte)74, "Haiti", (byte)114),
            ((byte)75, "Honduras", (byte)115),
            ((byte)76, "Hong Kong", (byte)116),
            ((byte)77, "Hungary", (byte)117),
            ((byte)78, "Iceland", (byte)118),
            ((byte)79, "India", (byte)119),
            ((byte)80, "Indonesia", (byte)120),
            ((byte)81, "Iran", (byte)121),
            ((byte)82, "Iraq", (byte)122),
            ((byte)83, "Ireland", (byte)123),
            ((byte)84, "Israel", (byte)124),
            ((byte)85, "Italy", (byte)125),
            ((byte)86, "Jamaica", (byte)126),
            ((byte)87, "Japan", (byte)127),
            ((byte)88, "Jordan", (byte)128),
            ((byte)89, "Kazakhstan", (byte)129),
            ((byte)90, "Kenya", (byte)130),
            ((byte)91, "Kiribati", (byte)131),
            ((byte)92, "Kuwait", (byte)132),
            ((byte)93, "Kyrgyzstan", (byte)133),
            ((byte)94, "Laos", (byte)134),
            ((byte)95, "Latvia", (byte)135),
            ((byte)96, "Lebanon", (byte)136),
            ((byte)97, "Lesotho", (byte)137),
            ((byte)98, "Liberia", (byte)138),
            ((byte)99, "Libya", (byte)139),
            ((byte)100, "Liechtenstein", (byte)140),
            ((byte)101, "Lithuania", (byte)141),
            ((byte)102, "Luxembourg", (byte)142),
            ((byte)103, "Macao", (byte)143),
            ((byte)104, "Madagascar", (byte)144),
            ((byte)105, "Malawi", (byte)145),
            ((byte)106, "Malaysia", (byte)146),
            ((byte)107, "Maldives", (byte)147),
            ((byte)108, "Mali", (byte)148),
            ((byte)109, "Malta", (byte)149),
            ((byte)110, "Martinique", (byte)150),
            ((byte)111, "Mauritania", (byte)151),
            ((byte)112, "Mauritius", (byte)152),
            ((byte)113, "Mexico", (byte)153),
            ((byte)114, "Micronesia", (byte)154),
            ((byte)115, "Moldova", (byte)155),
            ((byte)116, "Monaco", (byte)156),
            ((byte)117, "Mongolia", (byte)157),
            ((byte)118, "Montenegro", (byte)158),
            ((byte)119, "Morocco", (byte)159),
            ((byte)120, "Mozambique", (byte)160),
            ((byte)121, "Myanmar", (byte)161),
            ((byte)122, "Namibia", (byte)162),
            ((byte)123, "Nepal", (byte)163),
            ((byte)124, "Netherlands", (byte)164),
            ((byte)125, "New Caledonia", (byte)165),
            ((byte)126, "New Zealand", (byte)166),
            ((byte)127, "Nicaragua", (byte)167),
            ((byte)128, "Niger", (byte)168),
            ((byte)129, "Nigeria", (byte)169),
            ((byte)130, "North Korea", (byte)170),
            ((byte)131, "North Macedonia", (byte)171),
            ((byte)132, "Norway", (byte)172),
            ((byte)133, "Oman", (byte)173),
            ((byte)134, "Pakistan", (byte)174),
            ((byte)135, "Panama", (byte)175),
            ((byte)136, "Papua New Guinea", (byte)176),
            ((byte)137, "Paraguay", (byte)177),
            ((byte)138, "Peru", (byte)178),
            ((byte)139, "Philippines", (byte)179),
            ((byte)140, "Poland", (byte)180),
            ((byte)141, "Portugal", (byte)181),
            ((byte)142, "Puerto Rico", (byte)182),
            ((byte)143, "Qatar", (byte)183),
            ((byte)144, "Réunion", (byte)184),
            ((byte)145, "Romania", (byte)185),
            ((byte)146, "Russia", (byte)186),
            ((byte)147, "Rwanda", (byte)187),
            ((byte)148, "Saint Kitts and Nevis", (byte)188),
            ((byte)149, "Saint Lucia", (byte)189),
            ((byte)150, "Saint Vincent and the Grenadines", (byte)190),
            ((byte)151, "Samoa", (byte)191),
            ((byte)152, "San Marino", (byte)192),
            ((byte)153, "Sao Tome & Principe", (byte)193),
            ((byte)154, "Saudi Arabia", (byte)194),
            ((byte)155, "Senegal", (byte)195),
            ((byte)156, "Serbia", (byte)196),
            ((byte)157, "Seychelles", (byte)197),
            ((byte)158, "Sierra Leone", (byte)198),
            ((byte)159, "Singapore", (byte)199),
            ((byte)160, "Slovakia", (byte)200),
            ((byte)161, "Slovenia", (byte)201),
            ((byte)162, "Solomon Islands", (byte)202),
            ((byte)163, "Somalia", (byte)203),
            ((byte)164, "South Africa", (byte)204),
            ((byte)165, "South Korea", (byte)205),
            ((byte)166, "South Sudan", (byte)206),
            ((byte)167, "Spain", (byte)207),
            ((byte)168, "Sri Lanka", (byte)208),
            ((byte)169, "State of Palestine", (byte)209),
            ((byte)170, "Sudan", (byte)210),
            ((byte)171, "Suriname", (byte)211),
            ((byte)172, "Sweden", (byte)212),
            ((byte)173, "Switzerland", (byte)213),
            ((byte)174, "Syria", (byte)214),
            ((byte)175, "Taiwan", (byte)215),
            ((byte)176, "Tajikistan", (byte)216),
            ((byte)177, "Tanzania", (byte)217),
            ((byte)178, "Thailand", (byte)218),
            ((byte)179, "Timor-Leste", (byte)219),
            ((byte)180, "Togo", (byte)220),
            ((byte)181, "Tonga", (byte)221),
            ((byte)182, "Trinidad and Tobago", (byte)222),
            ((byte)183, "Tunisia", (byte)223),
            ((byte)184, "Turkey", (byte)224),
            ((byte)185, "Turkmenistan", (byte)225),
            ((byte)186, "Tuvalu", (byte)226),
            ((byte)187, "Uganda", (byte)227),
            ((byte)188, "Ukraine", (byte)228),
            ((byte)189, "United Arab Emirates", (byte)229),
            ((byte)190, "United Kingdom", (byte)230),
            ((byte)191, "United States", (byte)231),
            ((byte)192, "Uruguay", (byte)232),
            ((byte)193, "Uzbekistan", (byte)233),
            ((byte)194, "Vanuatu", (byte)234),
            ((byte)195, "Venezuela", (byte)235),
            ((byte)196, "Vietnam", (byte)236),
            ((byte)197, "Yemen", (byte)237),
            ((byte)198, "Zambia", (byte)238),
            ((byte)199, "Zimbabwe", (byte)239)
        );

    public static readonly ReadOnlyDictionary<int, string> DictCountriesByte = new ReadOnlyDictionary<int, string>(
        new Dictionary<int, string>
        {
            {(byte)1, "Afghanistan"},
            {(byte)2, "Albania"},
            {(byte)3, "Algeria"},
            {(byte)4, "Andorra"},
            {(byte)5, "Angola"},
            {(byte)6, "Antigua and Barbuda"},
            {(byte)7, "Argentina"},
            {(byte)8, "Armenia"},
            {(byte)9, "Australia"},
            {(byte)10, "Austria"},
            {(byte)11, "Azerbaijan"},
            {(byte)12, "Bahamas"},
            {(byte)13, "Bahrain"},
            {(byte)14, "Bangladesh"},
            {(byte)15, "Barbados"},
            {(byte)16, "Belarus"},
            {(byte)17, "Belgium"},
            {(byte)18, "Belize"},
            {(byte)19, "Benin"},
            {(byte)20, "Bhutan"},
            {(byte)21, "Bolivia"},
            {(byte)22, "Bosnia and Herzegovina"},
            {(byte)23, "Botswana"},
            {(byte)24, "Brazil"},
            {(byte)25, "Brunei"},
            {(byte)26, "Bulgaria"},
            {(byte)27, "Burkina Faso"},
            {(byte)28, "Burundi"},
            {(byte)29, "Cabo Verde"},
            {(byte)30, "Cambodia"},
            {(byte)31, "Cameroon"},
            {(byte)32, "Canada"},
            {(byte)33, "Central African Republic"},
            {(byte)34, "Chad"},
            {(byte)35, "Chile"},
            {(byte)36, "China"},
            {(byte)37, "Colombia"},
            {(byte)38, "Comoros"},
            {(byte)39, "Congo"},
            {(byte)40, "Costa Rica"},
            {(byte)41, "Côte d'Ivoire"},
            {(byte)42, "Croatia"},
            {(byte)43, "Cuba"},
            {(byte)44, "Cyprus"},
            {(byte)45, "Czech Republic"},
            {(byte)46, "Denmark"},
            {(byte)47, "Djibouti"},
            {(byte)48, "Dominica"},
            {(byte)49, "Dominican Republic"},
            {(byte)50, "DR Congo"},
            {(byte)51, "Ecuador"},
            {(byte)52, "Egypt"},
            {(byte)53, "El Salvador"},
            {(byte)54, "Equatorial Guinea"},
            {(byte)55, "Eritrea"},
            {(byte)56, "Estonia"},
            {(byte)57, "Eswatini"},
            {(byte)58, "Ethiopia"},
            {(byte)59, "Fiji"},
            {(byte)60, "Finland"},
            {(byte)61, "France"},
            {(byte)62, "Gabon"},
            {(byte)63, "Gambia"},
            {(byte)64, "Georgia"},
            {(byte)65, "Germany"},
            {(byte)66, "Ghana"},
            {(byte)67, "Gibraltar"},
            {(byte)68, "Greece"},
            {(byte)69, "Grenada"},
            {(byte)70, "Guatemala"},
            {(byte)71, "Guinea"},
            {(byte)72, "Guinea-Bissau"},
            {(byte)73, "Guyana"},
            {(byte)74, "Haiti"},
            {(byte)75, "Honduras"},
            {(byte)76, "Hong Kong"},
            {(byte)77, "Hungary"},
            {(byte)78, "Iceland"},
            {(byte)79, "India"},
            {(byte)80, "Indonesia"},
            {(byte)81, "Iran"},
            {(byte)82, "Iraq"},
            {(byte)83, "Ireland"},
            {(byte)84, "Israel"},
            {(byte)85, "Italy"},
            {(byte)86, "Jamaica"},
            {(byte)87, "Japan"},
            {(byte)88, "Jordan"},
            {(byte)89, "Kazakhstan"},
            {(byte)90, "Kenya"},
            {(byte)91, "Kiribati"},
            {(byte)92, "Kuwait"},
            {(byte)93, "Kyrgyzstan"},
            {(byte)94, "Laos"},
            {(byte)95, "Latvia"},
            {(byte)96, "Lebanon"},
            {(byte)97, "Lesotho"},
            {(byte)98, "Liberia"},
            {(byte)99, "Libya"},
            {(byte)100, "Liechtenstein"},
            {(byte)101, "Lithuania"},
            {(byte)102, "Luxembourg"},
            {(byte)103, "Macao"},
            {(byte)104, "Madagascar"},
            {(byte)105, "Malawi"},
            {(byte)106, "Malaysia"},
            {(byte)107, "Maldives"},
            {(byte)108, "Mali"},
            {(byte)109, "Malta"},
            {(byte)110, "Martinique"},
            {(byte)111, "Mauritania"},
            {(byte)112, "Mauritius"},
            {(byte)113, "Mexico"},
            {(byte)114, "Micronesia"},
            {(byte)115, "Moldova"},
            {(byte)116, "Monaco"},
            {(byte)117, "Mongolia"},
            {(byte)118, "Montenegro"},
            {(byte)119, "Morocco"},
            {(byte)120, "Mozambique"},
            {(byte)121, "Myanmar"},
            {(byte)122, "Namibia"},
            {(byte)123, "Nepal"},
            {(byte)124, "Netherlands"},
            {(byte)125, "New Caledonia"},
            {(byte)126, "New Zealand"},
            {(byte)127, "Nicaragua"},
            {(byte)128, "Niger"},
            {(byte)129, "Nigeria"},
            {(byte)130, "North Korea"},
            {(byte)131, "North Macedonia"},
            {(byte)132, "Norway"},
            {(byte)133, "Oman"},
            {(byte)134, "Pakistan"},
            {(byte)135, "Panama"},
            {(byte)136, "Papua New Guinea"},
            {(byte)137, "Paraguay"},
            {(byte)138, "Peru"},
            {(byte)139, "Philippines"},
            {(byte)140, "Poland"},
            {(byte)141, "Portugal"},
            {(byte)142, "Puerto Rico"},
            {(byte)143, "Qatar"},
            {(byte)144, "Réunion"},
            {(byte)145, "Romania"},
            {(byte)146, "Russia"},
            {(byte)147, "Rwanda"},
            {(byte)148, "Saint Kitts and Nevis"},
            {(byte)149, "Saint Lucia"},
            {(byte)150, "Saint Vincent and the Grenadines"},
            {(byte)151, "Samoa"},
            {(byte)152, "San Marino"},
            {(byte)153, "Sao Tome & Principe"},
            {(byte)154, "Saudi Arabia"},
            {(byte)155, "Senegal"},
            {(byte)156, "Serbia"},
            {(byte)157, "Seychelles"},
            {(byte)158, "Sierra Leone"},
            {(byte)159, "Singapore"},
            {(byte)160, "Slovakia"},
            {(byte)161, "Slovenia"},
            {(byte)162, "Solomon Islands"},
            {(byte)163, "Somalia"},
            {(byte)164, "South Africa"},
            {(byte)165, "South Korea"},
            {(byte)166, "South Sudan"},
            {(byte)167, "Spain"},
            {(byte)168, "Sri Lanka"},
            {(byte)169, "State of Palestine"},
            {(byte)170, "Sudan"},
            {(byte)171, "Suriname"},
            {(byte)172, "Sweden"},
            {(byte)173, "Switzerland"},
            {(byte)174, "Syria"},
            {(byte)175, "Taiwan"},
            {(byte)176, "Tajikistan"},
            {(byte)177, "Tanzania"},
            {(byte)178, "Thailand"},
            {(byte)179, "Timor-Leste"},
            {(byte)180, "Togo"},
            {(byte)181, "Tonga"},
            {(byte)182, "Trinidad and Tobago"},
            {(byte)183, "Tunisia"},
            {(byte)184, "Turkey"},
            {(byte)185, "Turkmenistan"},
            {(byte)186, "Tuvalu"},
            {(byte)187, "Uganda"},
            {(byte)188, "Ukraine"},
            {(byte)189, "United Arab Emirates"},
            {(byte)190, "United Kingdom"},
            {(byte)191, "United States"},
            {(byte)192, "Uruguay"},
            {(byte)193, "Uzbekistan"},
            {(byte)194, "Vanuatu"},
            {(byte)195, "Venezuela"},
            {(byte)196, "Vietnam"},
            {(byte)197, "Yemen"},
            {(byte)198, "Zambia"},
            {(byte)199, "Zimbabwe"},
        }
     );

    public static readonly ReadOnlyDictionary<int, string> DictCountries = new ReadOnlyDictionary<int, string>(
        new Dictionary<int, string>
            {
                {1, "Afghanistan"},
                {2, "Albania"},
                {3, "Algeria"},
                {4, "Andorra"},
                {5, "Angola"},
                {6, "Antigua and Barbuda"},
                {7, "Argentina"},
                {8, "Armenia"},
                {9, "Australia"},
                {10, "Austria"},
                {11, "Azerbaijan"},
                {12, "Bahamas"},
                {13, "Bahrain"},
                {14, "Bangladesh"},
                {15, "Barbados"},
                {16, "Belarus"},
                {17, "Belgium"},
                {18, "Belize"},
                {19, "Benin"},
                {20, "Bhutan"},
                {21, "Bolivia"},
                {22, "Bosnia and Herzegovina"},
                {23, "Botswana"},
                {24, "Brazil"},
                {25, "Brunei"},
                {26, "Bulgaria"},
                {27, "Burkina Faso"},
                {28, "Burundi"},
                {29, "Cabo Verde"},
                {30, "Cambodia"},
                {31, "Cameroon"},
                {32, "Canada"},
                {33, "Central African Republic"},
                {34, "Chad"},
                {35, "Chile"},
                {36, "China"},
                {37, "Colombia"},
                {38, "Comoros"},
                {39, "Congo"},
                {40, "Costa Rica"},
                {41, "Côte d'Ivoire"},
                {42, "Croatia"},
                {43, "Cuba"},
                {44, "Cyprus"},
                {45, "Czech Republic"},
                {46, "Denmark"},
                {47, "Djibouti"},
                {48, "Dominica"},
                {49, "Dominican Republic"},
                {50, "DR Congo"},
                {51, "Ecuador"},
                {52, "Egypt"},
                {53, "El Salvador"},
                {54, "Equatorial Guinea"},
                {55, "Eritrea"},
                {56, "Estonia"},
                {57, "Eswatini"},
                {58, "Ethiopia"},
                {59, "Fiji"},
                {60, "Finland"},
                {61, "France"},
                {62, "Gabon"},
                {63, "Gambia"},
                {64, "Georgia"},
                {65, "Germany"},
                {66, "Ghana"},
                {67, "Gibraltar"},
                {68, "Greece"},
                {69, "Grenada"},
                {70, "Guatemala"},
                {71, "Guinea"},
                {72, "Guinea-Bissau"},
                {73, "Guyana"},
                {74, "Haiti"},
                {75, "Honduras"},
                {76, "Hong Kong"},
                {77, "Hungary"},
                {78, "Iceland"},
                {79, "India"},
                {80, "Indonesia"},
                {81, "Iran"},
                {82, "Iraq"},
                {83, "Ireland"},
                {84, "Israel"},
                {85, "Italy"},
                {86, "Jamaica"},
                {87, "Japan"},
                {88, "Jordan"},
                {89, "Kazakhstan"},
                {90, "Kenya"},
                {91, "Kiribati"},
                {92, "Kuwait"},
                {93, "Kyrgyzstan"},
                {94, "Laos"},
                {95, "Latvia"},
                {96, "Lebanon"},
                {97, "Lesotho"},
                {98, "Liberia"},
                {99, "Libya"},
                {100, "Liechtenstein"},
                {101, "Lithuania"},
                {102, "Luxembourg"},
                {103, "Macao"},
                {104, "Madagascar"},
                {105, "Malawi"},
                {106, "Malaysia"},
                {107, "Maldives"},
                {108, "Mali"},
                {109, "Malta"},
                {110, "Martinique"},
                {111, "Mauritania"},
                {112, "Mauritius"},
                {113, "Mexico"},
                {114, "Micronesia"},
                {115, "Moldova"},
                {116, "Monaco"},
                {117, "Mongolia"},
                {118, "Montenegro"},
                {119, "Morocco"},
                {120, "Mozambique"},
                {121, "Myanmar"},
                {122, "Namibia"},
                {123, "Nepal"},
                {124, "Netherlands"},
                {125, "New Caledonia"},
                {126, "New Zealand"},
                {127, "Nicaragua"},
                {128, "Niger"},
                {129, "Nigeria"},
                {130, "North Korea"},
                {131, "North Macedonia"},
                {132, "Norway"},
                {133, "Oman"},
                {134, "Pakistan"},
                {135, "Panama"},
                {136, "Papua New Guinea"},
                {137, "Paraguay"},
                {138, "Peru"},
                {139, "Philippines"},
                {140, "Poland"},
                {141, "Portugal"},
                {142, "Puerto Rico"},
                {143, "Qatar"},
                {144, "Réunion"},
                {145, "Romania"},
                {146, "Russia"},
                {147, "Rwanda"},
                {148, "Saint Kitts and Nevis"},
                {149, "Saint Lucia"},
                {150, "Saint Vincent and the Grenadines"},
                {151, "Samoa"},
                {152, "San Marino"},
                {153, "Sao Tome & Principe"},
                {154, "Saudi Arabia"},
                {155, "Senegal"},
                {156, "Serbia"},
                {157, "Seychelles"},
                {158, "Sierra Leone"},
                {159, "Singapore"},
                {160, "Slovakia"},
                {161, "Slovenia"},
                {162, "Solomon Islands"},
                {163, "Somalia"},
                {164, "South Africa"},
                {165, "South Korea"},
                {166, "South Sudan"},
                {167, "Spain"},
                {168, "Sri Lanka"},
                {169, "State of Palestine"},
                {170, "Sudan"},
                {171, "Suriname"},
                {172, "Sweden"},
                {173, "Switzerland"},
                {174, "Syria"},
                {175, "Taiwan"},
                {176, "Tajikistan"},
                {177, "Tanzania"},
                {178, "Thailand"},
                {179, "Timor-Leste"},
                {180, "Togo"},
                {181, "Tonga"},
                {182, "Trinidad and Tobago"},
                {183, "Tunisia"},
                {184, "Turkey"},
                {185, "Turkmenistan"},
                {186, "Tuvalu"},
                {187, "Uganda"},
                {188, "Ukraine"},
                {189, "United Arab Emirates"},
                {190, "United Kingdom"},
                {191, "United States"},
                {192, "Uruguay"},
                {193, "Uzbekistan"},
                {194, "Vanuatu"},
                {195, "Venezuela"},
                {196, "Vietnam"},
                {197, "Yemen"},
                {198, "Zambia"},
                {199, "Zimbabwe"},
            }
        );
}